# Do not specify an `included` section at this top-level file. Specify the
# `--config` option pointing to this file, and the `--path` option to the files
# you wish to lint

excluded:
  - AWSAppSyncClient/Apollo


# Note: This feature is experimental. As of this writing (4-Dec-2018) warnings
# triggered by these rules should not be used to fail builds. Known issues:
# - unused_private_declaration incorrectly triggers on
#   AWSAppSyncClientConfiguration.oidcAuthProvider
analyzer_rules:
  - unused_import
  - unused_private_declaration

disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - nesting
  - redundant_optional_initialization
  - trailing_whitespace
  - type_body_length
  - type_name
  - identifier_name
  - unused_closure_parameter
  - weak_delegate

# configurable rules can be customized from this configuration file
closing_brace: error
comma: error
colon:
  severity: error
empty_count: warning
empty_enum_arguments: error
function_body_length:
  warning: 100
  error: 150
opening_brace: error
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
